set(_tracy_enable_default OFF)
if (NOT CMAKE_CONFIGURATION_TYPES AND CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(_tracy_enable_default ON)
endif()
option(TRACY_ENABLE "" ${_tracy_enable_default})
option(TRACY_LTO "" ON)
option(TRACY_NO_SAMPLING "" ON)
option(TRACY_ON_DEMAND "Only enable Tracy when a server is connected" ON)
add_subdirectory(${LIBRARIES_DIR}/tracy)

if (TRACY_ENABLE)
    target_compile_definitions(TracyClient PUBLIC TRACY_ENABLE=1)
endif()