echo Adding hooks for stop to "set scheduler-locking step"\n
define hookpost-run
  set scheduler-locking step
end
define hookpost-attach
  set scheduler-locking step
end
source libraries/lvgl/scripts/gdb/gdbinit.py
