#!/usr/bin/env python3
"""
Generate/update C++ LVGL wrapper classes from LVGL widget headers.

- Scans `libraries/lvgl/src/widgets/**/lv_*.h` for widgets
- Parses function prototypes prefixed with the widget name (e.g., lv_chart_*())
- Emits generated wrappers into `src/UI/Components/LVGL/generated/` as `Lv<Widget>.gen.h/.gen.cpp`
- Generated class names are suffixed with `Gen` (e.g., `LvLabelGen`)
- Also creates a thin non-generated header `src/UI/Components/LVGL/Lv<Widget>.h` if missing,
    defining `class Lv<Widget> : public Lv<Widget>Gen` with inherited constructors for manual overrides
- Updates `src/UI/Components/LVGL/CMakeLists.txt` to include new generated `.gen.cpp` files

Usage:
    python scripts/generate_lvgl_wrappers.py --all
    python scripts/generate_lvgl_wrappers.py --widget chart
    python scripts/generate_lvgl_wrappers.py --widgets chart,table,roller

Notes:
- Naming heuristic uses PascalCase of the widget token: 'chart' -> 'Chart', 'imgbtn' -> 'Imgbtn', 'buttonmatrix' -> 'Buttonmatrix'.
    You can provide explicit mappings via --map buttonmatrix:ButtonMatrix,imgbtn:ImgBtn if desired.
- Only functions whose first parameter is `lv_obj_t*` (or const) are wrapped as methods.
- Methods with names starting with get_/is_/has_ are marked const.
- If a function has a parameter of type `lv_anim_enable_t`, a default of LV_ANIM_ON is provided in the header.

This script aims to generate consistent wrappers matching local style, while being conservative with existing manual files.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path
from datetime import datetime
from typing import List, Tuple, Dict, Optional

ROOT = Path(__file__).resolve().parents[1]
WIDGETS_DIR = ROOT / "libraries" / "lvgl" / "src" / "widgets"
OUTPUT_DIR = ROOT / "src" / "UI" / "Components" / "LVGL"
OUTPUT_GEN_DIR = OUTPUT_DIR / "generated"
GEN_CMAKE_FILE = OUTPUT_GEN_DIR / "CMakeLists.txt"
CMAKE_FILE = OUTPUT_DIR / "CMakeLists.txt"
MARKER = "// AUTO-GENERATED BY generate_lvgl_wrappers.py -- DO NOT EDIT"

# Prototype matcher with optional preceding Doxygen comment and optional attributes after args
PROTO_WITH_DOC_RE = re.compile(
    r"(?P<doc>/\*\*.*?\*/)?\s*"  # optional /** ... */
    r"(?P<ret>[\w\s\*]+?)\s+"
    r"(?P<name>lv_([a-z0-9]+)_([A-Za-z0-9_]+))\s*"
    r"\((?P<args>[^)]*)\)\s*"
    r"(?:[A-Za-z_][^;]*)?;",
    re.S,
)
COMMENT_BLOCK_RE = re.compile(r"/\*.*?\*/", re.S)
COMMENT_LINE_RE = re.compile(r"//.*?$", re.M)
WS_RE = re.compile(r"\s+")

# C functions we should not emit as methods
EXCLUDE_SUFFIXES = {
    "create",  # handled by constructor
}

GETTER_PREFIXES = ("get_", "is_", "has_")


def strip_comments(text: str) -> str:
    text = COMMENT_BLOCK_RE.sub("\n", text)
    text = COMMENT_LINE_RE.sub("", text)
    return text


def to_pascal(s: str) -> str:
    # Basic PascalCase: split on underscores, uppercase first char of each token
    parts = s.replace("-", "_").split("_")
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def to_camel(s: str) -> str:
    parts = s.split("_")
    if not parts:
        return s
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def sanitize_doc(doc: str) -> str:
    """
    Remove C-API-specific lines from the Doxygen block that do not apply to wrappers.
    - Drop any "@param obj" lines, since the wrapper uses 'this' instead of an obj parameter.
    """
    if not doc:
        return doc
    lines = doc.splitlines()
    out: List[str] = []
    for ln in lines:
        # Remove lines like " * @param obj ..." with any spacing variations
        if re.search(r"\*\s*@param\s+obj\b", ln):
            continue
        out.append(ln)
    return "\n".join(out)


def get_lvgl_version() -> str:
    """Parse libraries/lvgl/lv_version.h to build a version string."""
    ver_file = ROOT / "libraries" / "lvgl" / "lv_version.h"
    major = minor = patch = None
    info = None
    try:
        txt = ver_file.read_text(encoding="utf-8")
        m = re.search(r"#define\s+LVGL_VERSION_MAJOR\s+(\d+)", txt)
        if m:
            major = m.group(1)
        m = re.search(r"#define\s+LVGL_VERSION_MINOR\s+(\d+)", txt)
        if m:
            minor = m.group(1)
        m = re.search(r"#define\s+LVGL_VERSION_PATCH\s+(\d+)", txt)
        if m:
            patch = m.group(1)
        m = re.search(r"#define\s+LVGL_VERSION_INFO\s+\"([^\"]*)\"", txt)
        if m:
            info = m.group(1)
    except Exception:
        pass
    if major and minor and patch:
        base = f"{major}.{minor}.{patch}"
    else:
        base = "unknown"
    if info and info.strip():
        return f"{base}-{info.strip()}"
    return base


def banner_lines(filename: str) -> List[str]:
    ts = datetime.now().isoformat(timespec="seconds")
    ver = get_lvgl_version()
    return [
        "/*",
        f" * {filename}",
        " *",
        f" *  AUTO-GENERATED: {ts} by scripts/generate_lvgl_wrappers.py",
        f" *  LVGL version: {ver}",
        " */",
        "",
    ]


def _active_macros_at_pos(text: str, pos: int) -> List[str]:
    """Return a list of active positive macros (e.g., LV_USE_TRANSLATION) at given position."""
    macros_stack: List[str] = []
    cur = 0
    for line in text.splitlines(True):
        ln = line.strip()
        # Handle entering guards
        m = re.match(r"#\s*ifdef\s+(\w+)", ln)
        if not m:
            m = re.match(r"#\s*if\s+defined\s*\(\s*(\w+)\s*\)", ln)
        if not m:
            m = re.match(r"#\s*if\s+(\w+)", ln)
        if m:
            macros_stack.append(m.group(1))
        elif re.match(r"#\s*endif\b", ln):
            if macros_stack:
                macros_stack.pop()
        # We ignore #else/#elif for now
        cur += len(line)
        if cur > pos:
            break
    # Only keep LVGL-style feature macros
    return [mac for mac in macros_stack if mac.startswith("LV_")]


def parse_prototypes(header_path: Path, widget_token: str) -> List[Tuple[str, str, str, str, List[Tuple[str, str, bool]], Optional[str], List[str]]]:
    """
    Return list of (ret_type, full_c_name, suffix, args_str, args[(type,name),...], docstr)
    for functions lv_<widget>_<suffix>();
    """
    raw = header_path.read_text(encoding="utf-8", errors="ignore")

    out = []
    for m in PROTO_WITH_DOC_RE.finditer(raw):
        doc = m.group('doc') or None
        ret_type = WS_RE.sub(" ", (m.group('ret') or '').strip())
        full_name = (m.group('name') or '').strip()
        name_match = re.match(r"lv_([a-z0-9]+)_([A-Za-z0-9_]+)", full_name)
        if not name_match:
            continue
        widget = name_match.group(1)
        suffix = name_match.group(2)
        args_raw = (m.group('args') or '').strip()
        args_str = WS_RE.sub(" ", re.sub(r"\s*\n\s*", " ", args_raw))
        if widget != widget_token:
            continue
        if suffix in EXCLUDE_SUFFIXES:
            continue
        # Determine active macros (guards) at the prototype's position
        guards = _active_macros_at_pos(raw, m.start())
        # parse args into list of (type, name)
        args: List[Tuple[str, str, bool]] = []  # (type, name, is_array)
        if args_raw and args_raw.strip() and args_raw.strip() != "void":
            for param in [p.strip() for p in args_raw.split(',') if p.strip()]:
                if param == '...':
                    args.append(('...', '', False))
                    continue
                if " " in param:
                    t, n = param.rsplit(" ", 1)
                    t_clean = WS_RE.sub(" ", t.strip())
                    is_array = '[' in n and ']' in n
                    n_clean = re.sub(r"\[.*\]", "", n.strip())
                    args.append((t_clean, n_clean, is_array))
                else:
                    args.append((param, f"arg{len(args)+1}", False))
        out.append((ret_type, full_name, suffix, args_str, args, doc, guards))
    return out


def first_param_is_lv_obj(args: List[Tuple[str, str]]) -> bool:
    if not args:
        return False
    t0 = args[0][0].strip()
    return re.match(r"^(?:const\s+)?lv_obj_t\s*\*", t0) is not None


## Old helper prototypes removed (use emit_header/emit_source below)


class MethodMeta:
    def __init__(self, ret_type: str, full_c: str, suffix: str, args: List[Tuple[str, str, bool]]):
        self.ret_type = ret_type.strip()
        self.full_c = full_c
        self.suffix = suffix
        self.args = args  # list of (type,name,is_array)
        self.name = to_camel(suffix)
        self.is_const = self.name.startswith("get") or self.name.startswith("is") or self.name.startswith("has")
        self.has_varargs = any(t.strip() == "..." for (t, _, _) in args)
        self.vfmt_full = None  # optional: C symbol for vfmt counterpart
        self.guards: List[str] = []
        # Map array index -> count index when pattern matches (e.g., size/count)
        self.array_count_pairs: Dict[int, int] = {}
        # Determine if return type is a C string pointer (kept for info only)
        self.ret_is_cstring = re.match(r"^(?:const\s+)?char\s*\*\s*$", self.ret_type) is not None

        # Detect array + count param patterns
        for i in range(1, len(self.args)):
            t_i, n_i, is_arr = self.args[i]
            if not is_arr:
                continue
            j = i + 1
            if j < len(self.args):
                t_j, n_j, _ = self.args[j]
                if re.match(r"^(size_t|uint32_t|int32_t)$", t_j) and re.search(r"(num|count|cnt|size|len)$", n_j):
                    self.array_count_pairs[i] = j

    def _is_cstring(self, t: str, is_arr: bool) -> bool:
        t_s = t.strip()
        if is_arr:
            # Arrays of strings handled via span<const char*>
            return False
        # Exactly one pointer to char and const-qualified
        return ("char" in t_s and t_s.count('*') == 1 and re.match(r"^const\s+?char\s*\*", t_s) is not None)

    def ret_type_cpp(self) -> str:
        """Return the wrapper return type (no C-string conversions)."""
        return self.ret_type

    def decl_args_str(self) -> str:
        items = []
        for idx in range(1, len(self.args)):
            (t, n, is_arr) = self.args[idx]
            t_s = t.strip()
            if t_s == "...":
                items.append("...")
                continue
            # Convert array+count into std::span where possible
            if is_arr:
                elem_t = t_s  # element type for span (e.g., const char*)
                items.append(f"std::span<{elem_t}> {n}")
                # Skip adding the count parameter in declaration if paired
                if idx in self.array_count_pairs:
                    continue
                continue
            # Skip count parameter if it pairs with previous array
            prev_idx = idx - 1
            if prev_idx in self.array_count_pairs and self.array_count_pairs.get(prev_idx) == idx:
                continue
            if t_s == "lv_anim_enable_t":
                items.append(f"{t} {n} = LV_ANIM_ON")
            else:
                items.append(f"{t} {n}")
        return ", ".join(items)

    def impl_args_str(self) -> str:
        """
        Args string for source definitions: no default values.
        Default arguments belong only in the declaration (header).
        """
        items = []
        for idx in range(1, len(self.args)):
            (t, n, is_arr) = self.args[idx]
            t_s = t.strip()
            if t_s == "...":
                items.append("...")
                continue
            if is_arr and idx in self.array_count_pairs:
                elem_t = t_s
                items.append(f"std::span<{elem_t}> {n}")
                continue
            # Skip count parameter if it pairs with previous array
            prev_idx = idx - 1
            if prev_idx in self.array_count_pairs and self.array_count_pairs.get(prev_idx) == idx:
                continue
            if is_arr:
                elem_t = t_s
                items.append(f"std::span<{elem_t}> {n}")
                continue
            items.append(f"{t} {n}")
        return ", ".join(items)

    def call_args_str(self) -> str:
        call_parts = []
        # Iterate preserving original C argument order
        for idx in range(1, len(self.args)):
            (t, n, is_arr) = self.args[idx]
            if t.strip() == "...":
                continue
            # If this is array with paired count, pass data() here
            if is_arr:
                call_parts.append(f"{n}.data()")
                # Count parameter will be handled by following branch
                continue
            # If this is the count that pairs with previous array, pass span.size()
            prev_idx = idx - 1
            if prev_idx in self.array_count_pairs and self.array_count_pairs.get(prev_idx) == idx:
                prev_name = self.args[prev_idx][1]
                call_parts.append(f"{prev_name}.size()")
                continue
            call_parts.append(n)
        return ", ".join(call_parts)


def build_methods(widget_token: str, protos: List[Tuple[str, str, str, str, List[Tuple[str, str, bool]], Optional[str], List[str]]]) -> List[MethodMeta]:
    methods: List[MethodMeta] = []
    # Map suffix -> proto for lookup (e.g., find _vfmt counterpart)
    proto_by_suffix: Dict[str, Tuple[str, str, str, str, List[Tuple[str, str, bool]], Optional[str], List[str]]] = {}
    for p in protos:
        proto_by_suffix[p[2]] = p
    for ret_type, full_c, suffix, _args_str, args, doc, guards in protos:
        if suffix in EXCLUDE_SUFFIXES:
            continue
        if not first_param_is_lv_obj([(t, n) for (t, n, _) in args]):
            continue
        mm = MethodMeta(ret_type, full_c, suffix, args)
        mm.doc = doc
        mm.guards = guards
        # If this method uses varargs, prefer a vfmt counterpart when available; else skip
        if mm.has_varargs:
            # Heuristic: if suffix ends with '_fmt', look for '_vfmt' variant taking va_list
            if suffix.endswith("_fmt"):
                vfmt_suffix = suffix[:-4] + "_vfmt"
                vproto = proto_by_suffix.get(vfmt_suffix)
                if vproto:
                    # confirm last arg is va_list
                    vargs = vproto[4]
                    if any(t.strip().endswith("va_list") for (t, _, _) in vargs):
                        mm.vfmt_full = vproto[1]
                        # keep method; we'll generate wrapper using va_list and call vfmt
                    else:
                        # no va_list variant, skip
                        continue
                else:
                    # no vfmt counterpart; skip varargs method
                    continue
            else:
                # unknown varargs without vfmt; skip
                continue
        methods.append(mm)
    return methods


def emit_header_gen(class_base_name: str, class_gen_name: str, widget_token: str, methods: List[MethodMeta]) -> str:
    lines: List[str] = []
    lines.extend(banner_lines(f"{class_base_name}.gen.h"))
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include \"UI/Components/LVGL/LvObj.h\"")
    # Include <span> if any method uses std::span
    if any(m.array_count_pairs or any(is_arr for (_, _, is_arr) in m.args[1:]) for m in methods):
        lines.append("#include <span>")
    # No std::string or string_view conversions; keep only <span> if needed
    lines.append("")
    lines.append("namespace UI")
    lines.append("{")
    lines.append(f"    {MARKER}")
    # Determine class-wide guards present on all methods
    if methods:
        class_guards = sorted(set.intersection(*(set(m.guards) for m in methods)))
    else:
        class_guards = []

    if class_guards:
        lines.append("")
    for g in class_guards:
        lines.append(f"    #if {g}")
    if class_guards:
        lines.append("")

    lines.append(f"    class {class_gen_name} : public LvObj")
    lines.append("    {")
    lines.append("      public:")
    lines.append(f"        {class_gen_name}(const std::string& name, LvObj& parent);")
    lines.append("")

    # Stream methods, grouping by guard sets beyond class-wide guards
    active_method_guards: List[str] = []
    for m in methods:
        if m.name == "refresh":
            lines.append("        void refresh();")
            lines.append("")
            continue
        extra_guards = [g for g in m.guards if g not in class_guards]
        if active_method_guards != extra_guards:
            # close previous
            for _ in reversed(active_method_guards):
                lines.append("        #endif")
            if active_method_guards:
                lines.append("")
            # open new
            for g in extra_guards:
                lines.append(f"        #if {g}")
            if extra_guards:
                lines.append("")
            active_method_guards = extra_guards
        # Emit Doxygen docstring if available, indented to class scope, with @param obj removed
        if getattr(m, 'doc', None):
            for dl in sanitize_doc(m.doc).splitlines():
                lines.append("        " + dl)
        const_str = " const" if m.is_const else ""
        lines.append(f"        {m.ret_type_cpp()} {m.name}({m.decl_args_str()}){const_str};")
        lines.append("")

    # Close any lingering method guard blocks
    for _ in reversed(active_method_guards):
        lines.append("        #endif")

    lines.append("")
    lines.append("      private:")
    lines.append("    };")

    if class_guards:
        lines.append("")
    for _ in reversed(class_guards):
        lines.append("    #endif")
    if class_guards:
        lines.append("")
    lines.append("} // namespace UI")
    lines.append("")
    return "\n".join(lines)


def emit_source_gen(class_base_name: str, class_gen_name: str, widget_token: str, methods: List[MethodMeta]) -> str:
    c_prefix = f"lv_{widget_token}_"
    lines: List[str] = []
    lines.extend(banner_lines(f"{class_base_name}.gen.cpp"))
    lines.append(f"#include \"{class_base_name}.gen.h\"")
    lines.append("#include \"Debug.h\"")
    # If any method uses varargs, include <cstdarg>
    if any(m.has_varargs for m in methods):
        lines.append("#include <cstdarg>")
    lines.append("")
    lines.append("namespace UI")
    lines.append("{")
    lines.append(f"    {MARKER}")
    # Determine class-wide guards present on all methods
    if methods:
        class_guards = sorted(set.intersection(*(set(m.guards) for m in methods)))
    else:
        class_guards = []
    if class_guards:
        lines.append("")
    for g in class_guards:
        lines.append(f"    #if {g}")
    if class_guards:
        lines.append("")
    lines.append(f"    {class_gen_name}::{class_gen_name}(const std::string& name, LvObj& parent)")
    lines.append(f"        : LvObj({c_prefix}create, name, parent)")
    lines.append("    {")
    lines.append("        UI_LOCK();")
    lines.append("    }")
    lines.append("")
    # Stream methods, grouping by guard sets beyond class-wide guards
    active_method_guards: List[str] = []
    for m in methods:
        # Build method signature in source
        if m.name == "refresh":
            lines.append(f"    void {class_gen_name}::refresh()")
            lines.append("    {")
            lines.append("        UI_LOCK();")
            lines.append(f"        {c_prefix}refresh(getRootPtr());")
            lines.append("    }")
            lines.append("")
            continue
        # Use implementation args (no defaults) in source definitions
        sig_args = m.impl_args_str()
        extra_guards = [g for g in m.guards if g not in class_guards]
        if active_method_guards != extra_guards:
            for _ in reversed(active_method_guards):
                lines.append("    #endif")
            if active_method_guards:
                lines.append("")
            for g in extra_guards:
                lines.append(f"    #if {g}")
            if extra_guards:
                lines.append("")
            active_method_guards = extra_guards
        if m.ret_type == "void":
            const_str = " const" if m.is_const else ""
            lines.append(f"    void {class_gen_name}::{m.name}({sig_args}){const_str}")
            lines.append("    {")
            lines.append("        UI_LOCK();")
            if m.has_varargs and m.vfmt_full:
                # Find the name of the last named parameter (format string) preceding '...'
                fmt_name = None
                for (t, n, _) in m.args[::-1]:
                    if t.strip() == "...":
                        continue
                    if n:
                        fmt_name = n
                        break
                if fmt_name is None:
                    fmt_name = "fmt"  # fallback
                lines.append("        va_list args;")
                lines.append(f"        va_start(args, {fmt_name});")
                # Pass C format string directly
                call_args = ", ".join(["getRootPtr()", fmt_name, "args"]
                                      ) if fmt_name else ", ".join(["getRootPtr()", "args"])
                lines.append(f"        {m.vfmt_full}({call_args});")
                lines.append("        va_end(args);")
            else:
                call_args = ", ".join(["getRootPtr()", m.call_args_str()]) if m.call_args_str() else "getRootPtr()"
                lines.append(f"        {m.full_c}({call_args});")
            lines.append("    }")
            lines.append("")
        else:
            const_str = " const" if m.is_const else ""
            lines.append(f"    {m.ret_type_cpp()} {class_gen_name}::{m.name}({sig_args}){const_str}")
            lines.append("    {")
            lines.append("        UI_LOCK();")
            call_args = ", ".join(["getRootPtr()", m.call_args_str()]) if m.call_args_str() else "getRootPtr()"
            lines.append(f"        return {m.full_c}({call_args});")
            lines.append("    }")
            lines.append("")
    # Close any lingering method guard blocks
    for _ in reversed(active_method_guards):
        lines.append("    #endif")
    for _ in reversed(class_guards):
        lines.append("    #endif")
    if class_guards:
        lines.append("")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def emit_derived_header_if_missing(class_base_name: str) -> Optional[str]:
    """Return text for a thin derived header if it does not already exist, else None."""
    # Do not mark with AUTO-GENERATED marker; this is intended for manual overrides later.
    lines: List[str] = []
    lines.append("#pragma once")
    lines.append("")
    lines.append(f"#include \"UI/Components/LVGL/generated/{class_base_name}.gen.h\"")
    lines.append("")
    lines.append("namespace UI")
    lines.append("{")
    lines.append(f"    class {class_base_name} : public {class_base_name}Gen")
    lines.append("    {")
    lines.append("      public:")
    # Inherit constructors from generated base for convenience
    lines.append(f"        using {class_base_name}Gen::{class_base_name}Gen;")
    lines.append("    };")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def write_if_allowed(path: Path, content: str, force_overwrite: bool) -> bool:
    if path.exists():
        existing = path.read_text(encoding="utf-8", errors="ignore")
        if not force_overwrite and MARKER not in existing:
            # Manual file; don't overwrite unless forced
            return False
        if existing == content:
            return False
    path.write_text(content, encoding="utf-8")
    return True


def ensure_parent_references_generated() -> None:
    """Ensure parent LVGL CMakeLists.txt adds the generated subdirectory."""
    try:
        if not CMAKE_FILE.exists():
            return
        cm = CMAKE_FILE.read_text(encoding="utf-8")
        if re.search(r"^\s*add_subdirectory\(\s*generated\s*\)", cm, re.M):
            return
        updated = "add_subdirectory(generated)\n\n" + cm
        CMAKE_FILE.write_text(updated, encoding="utf-8")
    except Exception:
        pass


def update_generated_cmake(new_gen_cpp_files: List[str]) -> None:
    """
    Maintain src/UI/Components/LVGL/generated/CMakeLists.txt with the list of generated sources.
    Entries should be of the form: ${CMAKE_CURRENT_SOURCE_DIR}/Lv<Widget>.gen.cpp
    """
    if not new_gen_cpp_files:
        return
    # Normalize to basenames within generated dir
    new_files = [Path(p).name for p in new_gen_cpp_files]
    existing_entries: List[str] = []
    header = """target_sources(
  DuetScreen.lib
  PRIVATE
"""
    footer = ")\n"
    if GEN_CMAKE_FILE.exists():
        txt = GEN_CMAKE_FILE.read_text(encoding="utf-8")
        # Extract existing lines with CURRENT_SOURCE_DIR
        for line in txt.splitlines():
            m = re.search(r"\$\{CMAKE_CURRENT_SOURCE_DIR\}/(.+\.gen\.cpp)$", line.strip())
            if m:
                # Normalize to basename to avoid duplicating 'generated/' prefix
                existing_entries.append(Path(m.group(1)).name)
    # Merge and sort unique
    merged = sorted(set(existing_entries) | set(new_files), key=lambda s: s.lower())
    body_lines = [f"  ${{CMAKE_CURRENT_SOURCE_DIR}}/{fname}" for fname in merged]
    content = header + "\n".join(body_lines) + "\n" + footer
    if not GEN_CMAKE_FILE.exists() or GEN_CMAKE_FILE.read_text(encoding="utf-8") != content:
        GEN_CMAKE_FILE.write_text(content, encoding="utf-8")


def discover_widget_headers() -> Dict[str, Path]:
    widgets: Dict[str, Path] = {}
    for hdr in WIDGETS_DIR.rglob("lv_*.h"):
        name = hdr.stem  # lv_chart
        if not name.startswith("lv_"):
            continue
        token = name[3:]
        widgets[token] = hdr
    return widgets


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate LVGL C++ wrappers")
    ap.add_argument("--all", action="store_true", help="Generate for all discovered widgets")
    ap.add_argument("--widget", help="Single widget token (e.g., chart)")
    ap.add_argument("--widgets", help="Comma-separated widget tokens")
    ap.add_argument("--map", help="Comma-separated explicit name mappings token:Class (e.g., buttonmatrix:ButtonMatrix)")
    ap.add_argument("--force-overwrite", action="store_true", help="Overwrite existing files, even manual ones")
    args = ap.parse_args()

    mappings: Dict[str, str] = {}
    if args.map:
        for item in args.map.split(','):
            if not item:
                continue
            token, cls = item.split(':', 1)
            mappings[token.strip()] = cls.strip()

    discovered = discover_widget_headers()

    selected: List[str] = []
    if args.all:
        selected = sorted(discovered.keys())
    elif args.widget:
        selected = [args.widget]
    elif args.widgets:
        selected = [s.strip() for s in args.widgets.split(',') if s.strip()]
    else:
        ap.error("Provide --all or --widget or --widgets")

    # Ensure generated output directory exists
    OUTPUT_GEN_DIR.mkdir(parents=True, exist_ok=True)

    generated_cpp: List[str] = []

    for token in selected:
        hdr = discovered.get(token)
        if not hdr:
            print(f"[skip] No header found for widget '{token}'")
            continue
        protos = parse_prototypes(hdr, token)
        methods = build_methods(token, protos)
        if not methods:
            print(f"[skip] No methods found for '{token}'")
            continue
        class_base = f"Lv{mappings.get(token, to_pascal(token))}"
        class_gen = f"{class_base}Gen"

        header_text = emit_header_gen(class_base, class_gen, token, methods)
        source_text = emit_source_gen(class_base, class_gen, token, methods)

        # Generated paths
        gen_h_rel = f"generated/{class_base}.gen.h"
        gen_cpp_rel = f"generated/{class_base}.gen.cpp"
        gen_h_path = OUTPUT_DIR / gen_h_rel
        gen_cpp_path = OUTPUT_DIR / gen_cpp_rel

        wrote_h = write_if_allowed(gen_h_path, header_text, args.force_overwrite)
        wrote_cpp = write_if_allowed(gen_cpp_path, source_text, args.force_overwrite)

        if wrote_h:
            print(f"[gen] {class_gen} -> {gen_h_rel}")
        else:
            print(f"[keep] {gen_h_rel} (existing)")

        if wrote_cpp:
            generated_cpp.append(gen_cpp_rel)
            print(f"[gen] {class_gen} -> {gen_cpp_rel}")
        else:
            print(f"[keep] {gen_cpp_rel} (existing)")

        # Create thin derived header if not present
        derived_h_path = OUTPUT_DIR / f"{class_base}.h"
        if not derived_h_path.exists():
            derived_text = emit_derived_header_if_missing(class_base)
            if derived_text:
                derived_h_path.write_text(derived_text, encoding="utf-8")
                print(f"[gen] {class_base} -> {class_base}.h (derived)")
        else:
            print(f"[keep] {class_base}.h (existing)")

    # Ensure parent refers to generated subdir and update its CMake file
    ensure_parent_references_generated()
    update_generated_cmake(generated_cpp)


if __name__ == "__main__":
    main()
