name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build DuetScreen
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DuetScreen
        uses: actions/checkout@v4
        with:
          path: DuetScreen
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Buildroot
        uses: actions/checkout@v4
        with:
          repository: Duet3D/buildroot-duetscreen
          path: buildroot-duetscreen
          submodules: recursive
          token: ${{ secrets.PAT }}

      - name: Generate Changelog
        id: changelog
        working-directory: DuetScreen
        run: |   
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          ./scripts/release_notes.sh >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Install Linux Dependencies
        run: |
          ./DuetScreen/scripts/install_prerequisites.sh
          ./buildroot-duetscreen/scripts/install_prerequisites.sh

      - name: Update Version
        working-directory: DuetScreen
        run: |
          ./scripts/update_version.sh "${{ github.ref_name }}"
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      
      - name: Push Version Update
        working-directory: DuetScreen
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update version to ${{ github.ref_name }}"
          git push origin HEAD:${{ github.ref_name }}

      - name: Build DuetScreen
        run: |
          cd buildroot-duetscreen
          make clean
          make duet3d_duetscreen_sd_defconfig
          DUETSCREEN_SRC="../DuetScreen" make duetscreen-rebuild

      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir artifacts
          cd DuetScreen
          ./scripts/create_upgrade.sh
          cp ./out/DuetScreen.tar.gz ../artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DuetScreen
          path: artifacts/*

      - name: Check Branch
        id: check_branch
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          echo "IS_MASTER=$([[ "$BRANCH_NAME" == "master" ]] && echo "true" || echo "false")" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/*
          body: ${{ env.CHANGELOG }}
          prerelease: ${{ steps.check_branch.outputs.IS_MASTER != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}