name: Run CTest

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: sudo apt-get update && ./scripts/install_prerequisites.sh

            - name: Configure project
              run: cmake --preset Simulation

            - name: Build project
              run: cmake --build --preset Simulation

            - name: Run CTest
              run: ctest --test-dir out/build/Simulation --output-on-failure
  